blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog', views.Blog, name='home'),
    path('blog/post', views.Post, name='post'),
    path('blog/postlist', views.PostList, name='list'),
    path('blog/<str:author>/postlist', views.UserPostList, name='userpostlist'),
    path('blog/postlist/<str:author>/<int:pk>/detail', views.PostDetail, name='detail'),
    path('blog/postlist/<str:author>/<int:pk>/edit', views.PostEdit, name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')), # [追加]
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.top, name='top'),
    path('', include('portfolio.urls')),
    path('', include('blog.urls')),
    path('mdeditor', include('mdeditor.urls')), # 追加
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe
from mdeditor.fields import MDTextField # 追加

# Create your models here.
class Posts(models.Model):
    author = models.ForeignKey('auth.user', on_delete=models.CASCADE)
    title = models.TextField(max_length=500)
    text = MDTextField()
    tags = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    update_date = models.DateTimeField(default=timezone.now)

    def update(self):
        self.update_date = timezone.now()
        self.save()

    def tag(self):
        return self.tags.split()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Posts
from mdeditor.fields import MDTextFormField # 追加

class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'] = forms.CharField(label='', widget=forms.TextInput(attrs={'class':'title', 'placeholder':'タイトル'}))
        self.fields['tags'] = forms.CharField(label='', widget=forms.TextInput(attrs={'class':'tag', 'placeholder':'タグをスペース区切りで入力'}))
        self.fields['text'] =  MDTextFormField()

    class Meta:
        model = Posts
        fields = ('title', 'tags', 'text')

blog/views.py
from django.shortcuts import render, redirect
from django import forms
from .forms import PostForm
from .models import Posts
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

# Create your views here.
def Blog(request):
    postlists = Posts.objects.order_by('created_date').reverse()[:10]
    print(len(postlists))
    return render(request, 'blog/blog.html', {'username': request.user, 'postlists': postlists, 'time': timezone.now()})

@login_required
def Post(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        Posts.objects.create(
            author_id=request.user.id,
            title=form.cleaned_data['title'],
            tags=form.cleaned_data['tags'],
            text=form.cleaned_data['text'],
        )
        return redirect('blog:home')
    return render(request, 'blog/post.html', {'form': form,'username': request.user})

def PostList(request):
    postlists = Posts.objects.all().order_by('created_date').reverse()
    return render(request, 'blog/postlist.html', {'postlists': postlists, 'username': request.user})

def UserPostList(request, author):
    postlists = Posts.objects.filter(author=get_object_or_404(User, username=author)).order_by('created_date').reverse()
    return render(request, 'blog/userpostlist.html', {'postlists': postlists, 'username': request.user, 'author': author})

def PostDetail(request, pk, author):
    post = get_object_or_404(Posts, pk=pk)
    if post.author == request.user:
        if request.method == 'POST':
            return redirect('blog:edit', pk=pk, author=author)
    return render(request, 'blog/postdetail.html', {'post': post, 'username': request.user})

@login_required
def PostEdit(request, pk, author):
    if get_object_or_404(Posts, pk=pk).author == request.user:
        post = get_object_or_404(Posts, pk=pk)
        form = PostForm(request.POST or None, instance=post)
        if request.method == 'POST' and form.is_valid():
            if 'edit' in request.POST:
                post.update()
                return redirect('blog:detail', pk=pk, author=author)
            if 'del' in request.POST:
                post.delete()
                return redirect('blog:list')
        return render(request, 'blog/postedit.html', {'form': form, 'username': request.user})
    return redirect('blog:detail', pk=pk, author=author)

templates/blog/base.html
{% extends 'main.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/blog.css' %}">
{% endblock stylesheet %}

{% block contents %}
    <div class="contentsWall">
        <div class="contentsIn">
            {% block contentsIn %}
                {% block contentsId %}<div>{% endblock contentsId %}
                </div>
            {% endblock contentsIn %}
        </div>
    </div>
{% endblock contents %}

templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block title %}
Blog
{% endblock title %}

{% block titleh1 %}
Blog
{% endblock titleh1 %}

{% block contentsIn %}
<div id="blog">
    <h1>最新記事</h1>
    {% for postlist in postlists %}
        <div>
            <a href="{% url 'blog:detail' pk=postlist.pk author=postlist.author %}">{{postlist}}</a>
            <p>by <a href="{% url 'blog:userpostlist' author=postlist.author %}">{{postlist.author}}</a>　作成:{{postlist.created_date|timesince}}前　最終更新:{{postlist.update_date|timesince}}</p>
        </div>
    {% endfor %}
    {% if postlists|length == 10 %}
        <a href="{% url 'blog:list'%}">全て見る</a>
    {% endif %}
</div>
{% endblock contentsIn %}

templates/blog/post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/post.css' %}">
{% endblock stylesheet %}

{% block title %}
Post
{% endblock title %}

{% block titleh1 %}
Post
{% endblock titleh1 %}

{% block contents %}
{% block contentsId %}
    <div id="post">
{% endblock contentsId %}
    <form method="POST" novalidate>
        <ul>
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_ul}}
        </ul>
        {% block button %}
            <button type="submit">投稿</button>
        {% endblock button %}
    </form>
</div>
{% endblock contents %}

{% block footer %}
{% endblock footer %}

templates/blog/postdetail.html
{% extends 'blog/base.html' %}
{% load markdown_extras %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/postdetail.css' %}">
    <link href="{% static 'mdeditor/css/editormd.min.css' %}" rel="stylesheet">
    <link href="{% static 'mdeditor/css/editormd.preview.css' %}" rel="stylesheet">
{% endblock stylesheet %}

{% block title %}
PostDetail
{% endblock title %}

{% block titleh1 %}
PostDetail
{% endblock titleh1 %}

{% block contentsIn %}
<div id="postdetail">
    <div class="postdata">
        <a href="{% url 'blog:userpostlist' author=post.author %}">{{ post.author }}</a>
        <p>Last Update:{{ post.update_date }}</p>
    </div>
    <div class="postcontents">
        <h1>{{ post }}</h1>
        <div class="tags">
            <ul>
                {% for tag in post.tag %}
                    <li><a>{{tag}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div id="content">{{ post.text|markdown|safe }}</div>
    </div>
    {% if post.author == username %}
        <form method="POST" novalidate>
                {% csrf_token %}
            <button type="submit">編集</button>
        </form>
    {% endif %}
    <script src="{% static 'mdeditor/js/jquery.min.js' %}"></script>
    <script src="{% static 'mdeditor/js/editormd.min.js' %}"></script>
    <script src="{% static 'mdeditor/js/lib/marked.min.js' %}"></script>
    <script src="{% static 'mdeditor/js/lib/prettify.min.js' %}"></script>
    <script src="{% static 'mdeditor/js/lib/raphael.min.js' %}"></script>
    <script src="{% static 'mdeditor/js/lib/underscore.min.js' %}"></script>
    <script src="{% static 'mdeditor/js/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'mdeditor/js/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'mdeditor/js/lib/jquery.flowchart.min.js' %}"></script>
    <script>
    $(function () {
        editormd.markdownToHTML("content", {
            emoji           : true,
            taskList        : true,
            tex             : true,
            flowChart       : true,
            sequenceDiagram : true,
        });
        $(".reference-link").each(function (i,obj) {
            console.log(obj)
        })
    })
    </script>
</div>
{% endblock contentsIn %}

templates/blog/postedit.html
{% extends 'blog/post.html' %}

{% block title %}
PostEdit
{% endblock title %}

{% block titleh1 %}
PostEdit
{% endblock titleh1 %}

{% block contentsId %}
    <div id="postedit">
{% endblock contentsId %}

{% block button %}
    <button type="submit" name="edit">編集</button></a>
    <button type="submit" name="del" onclick="return confirm("本当に削除しますか？")";>消去</button>
{% endblock button %}

templates/blog/postlist.html
{% extends 'blog/blog.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/postlist.css' %}">
{% endblock stylesheet %}

{% block title %}
PostList
{% endblock title %}

{% block titleh1 %}
PostList
{% endblock titleh1 %}

{% block contentsIn %}
<div id="postlist">
    <h1>記事一覧</h1>
    {% for postlist in postlists %}
        <div>
            <a href="{% url 'blog:detail' pk=postlist.pk author=postlist.author %}">{{postlist}}</a>
            <p>by <a href="{% url 'blog:userpostlist' author=postlist.author %}">{{postlist.author}}</a>　作成:{{postlist.created_date|timesince}}前　最終更新:{{postlist.update_date|timesince}}</p>
        </div>
    {% endfor %}
</div>
{% endblock contentsIn %}

templates/blog/userpostlist.html
{% extends 'blog/base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/postlist.css' %}">
{% endblock stylesheet %}

{% block title %}
PostList
{% endblock title %}

{% block titleh1 %}
PostList
{% endblock titleh1 %}

{% block contentsIn %}
<div id="postlist">
    <h1>{{ author }}の記事一覧</h1>
    {% for postlist in postlists %}
        <div>
            <a href="{% url 'blog:detail' pk=postlist.pk author=postlist.author %}">{{postlist}}</a>
            <p>by <a>{{postlist.author}}</a>　{{postlist.update_date|timesince}}前</p>
        </div>
    {% endfor %}
</div>
{% endblock contentsIn %}