blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog', views.Blog, name='home'),
    path('blog/post', views.Post, name='post'),
    path('blog/postlist', views.PostList, name='list'),
    path('blog/<str:author>/postlist', views.UserPostList, name='userpostlist'),
    path('blog/postlist/<str:author>/<int:pk>/detail', views.PostDetail, name='detail'),
    path('blog/postlist/<str:author>/<int:pk>/edit', views.PostEdit, name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')), # [追加]
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.top, name='top'),
    path('', include('portfolio.urls')),
    path('', include('blog.urls')),
    path('mdeditor', include('mdeditor.urls')), # 追加
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('portfolio', views.Portfolio, name='home'),
    path('portfolio/<str:username>/<int:pk>/detail', views.ContactDetail, name='detail'),
    path('portfolio/<str:username>/<int:pk>/edit', views.ContactEdit, name='edit'),
]

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
    <head>
    {% block extrahead %}
        <meta http-equiv="content-type" charset="utf-8">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
        {% block stylesheet %}
        {% endblock stylesheet %}
        <script src="{% static 'mysite.js' %}"></script>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div id="top">
            <header>
                <div class="header">
                    <div class="headerTitle">
                        <h1>{% block titleh1 %}{% endblock %}</h1>
                    </div>
                    <div class="headerNav">
                        <ul>
                            <li><a href="{% url 'top' %}">Top</a></li>
                            <li><a href="{% url 'blog:home' %}">⌵ Blog<span></span></a>
                                <ul>
                                    <li><a href="{% url 'blog:home' %}"><p>>Home</p></a></li>
                                    {% if username.id != None %}
                                        {% if 'post' not in request.path or 'postlist' in request.path%}
                                            <li><a href="{% url 'blog:post' %}"><p>>Post</p></a></li>
                                        {% endif %}
                                    {% endif %}
                                    {% if 'postlist' not in request.path%}
                                        <li><a href="{% url 'blog:list' %}"><p>>PostList</p></a></li>
                                    {% endif %}
                                </ul>
                            </li>
                            <li><a href="{% url 'portfolio:home' %}">⌵ Portfolio<span></span></a>
                                <ul>
                                {% if '/portfolio' == request.path %}
                                    <li><a href="#top"><p>>Home</p></a></li>
                                    <li><a href="#work"><p>>work</p></a></li>
                                    <li><a href="#contact"><p>>contact</p></a></li>
                                {% else %}
                                    <li><a href="{% url 'portfolio:home' %}#top"><p>>Home</p></a></li>
                                    <li><a href="{% url 'portfolio:home' %}#work"><p>>work</p></a></li>
                                    <li><a href="{% url 'portfolio:home' %}#contact"><p>>contact</p></a></li>
                                {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="headerUser">
                    {% block headerUser %}
                        {% if username.id != None %}
                            {% if username.is_superuser == 1%}
                            <ul>
                                <li>
                                    <a href="">⌵ ログイン中(admin)<span></span></a>
                                    <ul>
                                        <li><a href="{% url 'mypage' username=request.user %}">>MyPage</a></li>
                                        <li><a href="{% url 'logout' %}"><p>>Logout</p></a></li>
                                    </ul>
                                </li>
                            </ul>
                            {% else %}
                            <ul>
                                <li>
                                    <a href="">⌵ ログイン中(user)<span></span></a>
                                    <ul>
                                        <li><a href="{% url 'mypage' username=request.user %}">>MyPage</a></li>
                                        <li><a href="{% url 'logout' %}"><p>>Logout</p></a></li>
                                    </ul>
                                </li>
                            </ul>
                            {% endif %}
                        {% else %}
                            <ul>
                                <li><a href="">⌵ Account<span></span></a>
                                    <ul>
                                        <li><a href="{% url 'signup' %}">>Signup</a></li>
                                        <li><a href="{% url 'login' %}"><p>>Login</p></a></li>
                                    </ul>
                                </li>
                            </ul>
                        {% endif %}
                    {% endblock headerUser %}
                    </div>
                </div>
            </header>
            <div id="contents">
                {% block contents %}
                {% endblock contents %}
            </div>
            <footer>
            {% block footer %}
                <div class="footerIn">
                    <small>©2020 Yuta Saikawa All Right Reserved.</small><br>
                    <small><a href="{% url 'admin:index' %}">管理者サイト</a></small>
                </div>
            {% endblock footer %}
            </footer>
        </div>
    </body>
    {% endblock %}
</html>